In [1]:
import pandas as pd

In [2]:
df_g = pd.read_csv("../data/genotype/genotype_matrix_knn.csv")
df_p = pd.read_csv("../data/phenotype/phenotype_matrix.csv")

In [3]:
df_g.head()

,Genotype,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
0,HEB_01_001,2,2.0,2,2,2,2,2,0,0,...,0,0.0,0,0,0,0,0,0,0,0
1,HEB_01_003,2,2.0,2,2,2,2,2,1,2,...,0,0.0,0,0,0,0,0,0,0,0
2,HEB_01_004,2,2.0,2,2,2,2,2,0,0,...,1,1.0,1,1,1,1,2,2,2,2
3,HEB_01_005,2,2.0,2,2,2,2,2,1,1,...,0,0.0,0,0,0,0,0,0,0,0
4,HEB_01_013,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,2,2,2,2

In [4]:
df_p.head()

     Genotype   HEA    TGW   HEI   RIP   PM
0  HEB_01_001  62.0  53.63  53.0  35.0  7.0
1  HEB_01_003  67.0  57.62  58.0  34.0  5.0
2  HEB_01_004  57.0  52.15  74.0  40.0  1.0
3  HEB_01_005  69.0  54.16  60.0  34.0  6.0
4  HEB_01_013  64.0  51.40  60.0  34.0  1.0

In [5]:
#
# params
#
markers = ["SCRI_RS_170337", "SCRI_RS_155612"] 
trait = "RIP"

In [6]:
mask_g_AA = df_g[markers].sum(axis=1) == 0
mask_g_BB = df_g[markers].sum(axis=1) == 4
mask_g_AB = (df_g[markers[0]]==0) & (df_g[markers[1]]==2)
mask_g_BA = (df_g[markers[0]]==2) & (df_g[markers[1]]==0)

In [7]:
df_g[mask_g_AA]

,Genotype,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
0,HEB_01_001,2,2.0,2,2,2,2,2,0,0,...,0,0.0,0,0,0,0,0,0,0,0
2,HEB_01_004,2,2.0,2,2,2,2,2,0,0,...,1,1.0,1,1,1,1,2,2,2,2
5,HEB_01_021,2,2.0,2,2,2,2,2,0,0,...,0,0.0,2,2,2,2,2,2,2,2
8,HEB_01_025,0,0.0,0,0,0,0,0,0,0,...,0,0.0,2,2,2,2,2,2,2,2
10,HEB_01_031,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
29,HEB_01_085,0,0.0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0,0
34,HEB_01_092,0,0.0,0,0,0,0,0,0,0,...,1,1.0,0,0,0,0,0,0,0,0
35,HEB_01_093,0,0.0,0,0,0,0,0,0,0,...,0,0.0,0,2,2,2,2,2,2,2
38,HEB_01_099,1,1.0,1,1,1,1,2,2,2,...,0,0.0,0,0,0,0,0,0,0,0
41,HEB_01_104,0,0.0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0,2
73,HEB_10_046,1,1.0,1,1,1,1,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
76,HEB_10_050,0,0.0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0,0
84,HEB_10_074,2,2.0,2,2,2,2,2,0,0,...,1,1.0,1,1,1,1,1,1,1,1
100,HEB_10_133,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,0,0,0,0
104,HEB_10_139,2,2.0,2,2,2,2,0,0,0,...,2,2.0,2,2,2,2,1,1,1,1
107,HEB_10_142,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
110,HEB_10_171,0,0.0,0,0,0,0,0,0,0,...,0,0.0,2,2,2,2,2,2,2,2
112,HEB_10_173,1,0.0,1,1,1,1,1,0,0,...,0,0.0,2,2,2,2,2,2,2,2
113,HEB_10_174,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
114,HEB_10_175,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
117,HEB_10_184,0,0.0,0,0,0,0,0,0,0,...,0,0.0,2,2,2,2,2,2,2,2
118,HEB_10_187,2,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
119,HEB_10_190,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2

In [8]:
df_g[mask_g_AB]

,Genotype,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
94,HEB_10_115,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2

In [9]:
df_g[mask_g_BB]

,Genotype,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
1,HEB_01_003,2,2.0,2,2,2,2,2,1,2,...,0,0.0,0,0,0,0,0,0,0,0
4,HEB_01_013,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,2,2,2,2
6,HEB_01_022,2,2.0,2,2,2,2,2,0,0,...,2,2.0,2,2,2,2,2,2,2,2
7,HEB_01_023,2,2.0,2,2,2,2,2,2,2,...,1,1.0,2,2,2,2,2,2,2,2
9,HEB_01_030,2,2.0,2,2,2,2,2,2,2,...,1,1.0,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,HEB_10_140,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,0,0,0,0
106,HEB_10_141,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,2,2,2,2
109,HEB_10_155,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,2,2,2,2
111,HEB_10_172,0,1.0,0,0,0,0,0,2,2,...,0,0.0,2,2,2,2,2,2,2,2
115,HEB_10_176,2,2.0,2,2,2,2,2,2,2,...,0,0.0,2,2,2,2,2,2,2,2

In [10]:
df_g[mask_g_BA]

Empty DataFrame
Columns: [Genotype, SCRI_RS_136200, SCRI_RS_156845, SCRI_RS_133377, SCRI_RS_190048, BOPA2_12_31497, SCRI_RS_141771, SCRI_RS_209516, BOPA2_12_31284, SCRI_RS_185319, SCRI_RS_198643, BK_12, BK_14, BK_15, BK_16, BOPA2_12_30871, BOPA2_12_30872, SCRI_RS_170337, SCRI_RS_155612, BOPA1_7032_201, SCRI_RS_120182, BOPA2_12_30657, SCRI_RS_154981, SCRI_RS_194318, SCRI_RS_201800, SCRI_RS_158928, BOPA1_6384_866, SCRI_RS_224846, BOPA1_946_2500, SCRI_RS_144592, SCRI_RS_170235, SCRI_RS_240011, SCRI_RS_185710, BOPA1_4136_869, BOPA1_6911_866, BOPA1_2284_1738, BOPA1_4434_804, SCRI_RS_153531, SCRI_RS_167713, BOPA1_7187_382, BOPA1_7660_476, BOPA2_12_10719, BOPA2_12_31383, SCRI_RS_110043, BOPA1_4037_916, SCRI_RS_9469, SCRI_RS_133539, SCRI_RS_200291, BOPA2_12_30897, SCRI_RS_196853, SCRI_RS_88704, BOPA1_8632_1809, SCRI_RS_119261, SCRI_RS_155456, SCRI_RS_157236, SCRI_RS_176114, SCRI_RS_182039, SCRI_RS_211894, SCRI_RS_237481, BOPA1_11591_265, SCRI_RS_129223, SCRI_RS_135112, SCRI_RS_144778, SCRI_RS_222876, BOPA1_111_499, BOPA1_3180_1771, BOPA1_871_462, BOPA1_2464_1228, BOPA2_12_30690, SCRI_RS_139840, SCRI_RS_209551, SCRI_RS_142314, SCRI_RS_198883, SCRI_RS_106163, SCRI_RS_161490, BOPA2_12_10487, BOPA2_12_10950, SCRI_RS_172784, SCRI_RS_204274, SCRI_RS_234587, SCRI_RS_44952, SCRI_RS_152664, SCRI_RS_156013, SCRI_RS_174077, SCRI_RS_194653, SCRI_RS_116590, SCRI_RS_172136, SCRI_RS_73620, SCRI_RS_170209, SCRI_RS_139106, SCRI_RS_139115, SCRI_RS_142982, SCRI_RS_139737]
Index: []

[0 rows x 93 columns]

In [11]:
mask_p_AA = df_p["Genotype"].isin(df_g[mask_g_AA]["Genotype"]) 
mask_p_BB = df_p["Genotype"].isin(df_g[mask_g_BB]["Genotype"]) 
mask_p_AB = df_p["Genotype"].isin(df_g[mask_g_AB]["Genotype"]) 
mask_p_BA = df_p["Genotype"].isin(df_g[mask_g_BA]["Genotype"])

In [12]:
mask_g_AA

0       True
1      False
2       True
3      False
4      False
       ...
115    False
116    False
117     True
118     True
119     True
Length: 120, dtype: bool

In [13]:
df_p[mask_g_AA][trait].mean()

np.float64(35.04347826086956)

In [14]:
df_p[mask_g_AB][trait].mean()

np.float64(35.0)

In [15]:
df_p[mask_g_BA][trait].mean()

nan

In [16]:
df_p[mask_g_BB][trait].mean()

np.float64(31.97459673524582)