In [17]:
import pandas as pd

In [18]:
df_g = pd.read_csv("../data/genotype/genotype_matrix_knn.csv")
df_p = pd.read_csv("../data/phenotype/phenotype_matrix.csv")

In [19]:
df_g.head()

,Genotype,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
0,HEB_01_001,2,2.0,2,2,2,2,2,0,0,...,0,0.0,0,0,0,0,0,0,0,0
1,HEB_01_003,2,2.0,2,2,2,2,2,1,2,...,0,0.0,0,0,0,0,0,0,0,0
2,HEB_01_004,2,2.0,2,2,2,2,2,0,0,...,1,1.0,1,1,1,1,2,2,2,2
3,HEB_01_005,2,2.0,2,2,2,2,2,1,1,...,0,0.0,0,0,0,0,0,0,0,0
4,HEB_01_013,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,2,2,2,2

In [20]:
df_p.head()

     Genotype   HEA    TGW   HEI   RIP   PM
0  HEB_01_001  62.0  53.63  53.0  35.0  7.0
1  HEB_01_003  67.0  57.62  58.0  34.0  5.0
2  HEB_01_004  57.0  52.15  74.0  40.0  1.0
3  HEB_01_005  69.0  54.16  60.0  34.0  6.0
4  HEB_01_013  64.0  51.40  60.0  34.0  1.0

In [21]:
markers = ["BK_15", "SCRI_RS_133377"]

In [22]:
mask_g_AA = df_g[markers].sum(axis=1) == 0
mask_g_BB = df_g[markers].sum(axis=1) == 4
mask_g_AB = (df_g[markers[0]]==0) & (df_g[markers[1]]==2)
mask_g_BA = (df_g[markers[0]]==2) & (df_g[markers[1]]==0)

In [23]:
df_g[mask_g_AA]

,Genotype,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
8,HEB_01_025,0,0.0,0,0,0,0,0,0,0,...,0,0.0,2,2,2,2,2,2,2,2
10,HEB_01_031,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
29,HEB_01_085,0,0.0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0,0
34,HEB_01_092,0,0.0,0,0,0,0,0,0,0,...,1,1.0,0,0,0,0,0,0,0,0
35,HEB_01_093,0,0.0,0,0,0,0,0,0,0,...,0,0.0,0,2,2,2,2,2,2,2
41,HEB_01_104,0,0.0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0,2
42,HEB_01_106,0,0.0,0,0,0,0,2,1,1,...,0,0.0,0,0,0,0,0,0,0,0
76,HEB_10_050,0,0.0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0,0
79,HEB_10_055,0,0.0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0,0
94,HEB_10_115,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
107,HEB_10_142,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
110,HEB_10_171,0,0.0,0,0,0,0,0,0,0,...,0,0.0,2,2,2,2,2,2,2,2
113,HEB_10_174,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
114,HEB_10_175,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
116,HEB_10_182,0,0.0,0,0,0,0,0,0,0,...,1,1.0,2,2,2,2,2,2,2,2
117,HEB_10_184,0,0.0,0,0,0,0,0,0,0,...,0,0.0,2,2,2,2,2,2,2,2
118,HEB_10_187,2,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2
119,HEB_10_190,0,0.0,0,0,0,0,0,0,0,...,2,2.0,2,2,2,2,2,2,2,2

In [24]:
df_g[mask_g_AB]

,Genotype,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
0,HEB_01_001,2,2.0,2,2,2,2,2,0,0,...,0,0.0,0,0,0,0,0,0,0,0
2,HEB_01_004,2,2.0,2,2,2,2,2,0,0,...,1,1.0,1,1,1,1,2,2,2,2
5,HEB_01_021,2,2.0,2,2,2,2,2,0,0,...,0,0.0,2,2,2,2,2,2,2,2
84,HEB_10_074,2,2.0,2,2,2,2,2,0,0,...,1,1.0,1,1,1,1,1,1,1,1
104,HEB_10_139,2,2.0,2,2,2,2,0,0,0,...,2,2.0,2,2,2,2,1,1,1,1

In [25]:
df_g[mask_g_BB]

,Genotype,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
1,HEB_01_003,2,2.0,2,2,2,2,2,1,2,...,0,0.0,0,0,0,0,0,0,0,0
3,HEB_01_005,2,2.0,2,2,2,2,2,1,1,...,0,0.0,0,0,0,0,0,0,0,0
4,HEB_01_013,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,2,2,2,2
6,HEB_01_022,2,2.0,2,2,2,2,2,0,0,...,2,2.0,2,2,2,2,2,2,2,2
7,HEB_01_023,2,2.0,2,2,2,2,2,2,2,...,1,1.0,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,HEB_10_140,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,0,0,0,0
106,HEB_10_141,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,2,2,2,2
108,HEB_10_150,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,2,2,2,2
109,HEB_10_155,2,2.0,2,2,2,2,2,2,2,...,2,2.0,2,2,2,2,2,2,2,2
115,HEB_10_176,2,2.0,2,2,2,2,2,2,2,...,0,0.0,2,2,2,2,2,2,2,2

In [26]:
df_g[mask_g_BA]

,Genotype,SCRI_RS_136200,SCRI_RS_156845,SCRI_RS_133377,SCRI_RS_190048,BOPA2_12_31497,SCRI_RS_141771,SCRI_RS_209516,BOPA2_12_31284,SCRI_RS_185319,...,SCRI_RS_174077,SCRI_RS_194653,SCRI_RS_116590,SCRI_RS_172136,SCRI_RS_73620,SCRI_RS_170209,SCRI_RS_139106,SCRI_RS_139115,SCRI_RS_142982,SCRI_RS_139737
39,HEB_01_101,0,0.0,0,0,0,0,0,2,2,...,0,0.0,0,0,0,0,0,0,0,1
53,HEB_01_131,0,0.0,0,0,2,2,2,2,2,...,2,2.0,2,1,1,2,2,2,2,2
54,HEB_01_132,0,0.0,0,0,2,2,2,2,2,...,0,0.0,0,0,0,2,2,2,2,2
56,HEB_01_134,0,0.0,0,0,2,2,2,2,2,...,0,0.0,0,0,0,2,2,2,2,2
78,HEB_10_054,0,0.0,0,0,0,0,1,1,1,...,2,2.0,2,2,2,2,2,2,2,2
82,HEB_10_070,0,0.0,0,0,0,0,0,2,2,...,0,0.0,0,0,0,0,0,0,0,1
93,HEB_10_114,0,0.0,0,0,0,0,0,2,2,...,2,2.0,2,2,2,2,2,2,2,2
97,HEB_10_124,0,0.0,0,0,2,2,2,2,2,...,2,2.0,2,2,2,2,0,0,0,0
98,HEB_10_131,0,0.0,0,0,0,0,2,2,2,...,2,2.0,2,2,2,2,1,1,1,1
111,HEB_10_172,0,1.0,0,0,0,0,0,2,2,...,0,0.0,2,2,2,2,2,2,2,2

In [27]:
mask_p_AA = df_p["Genotype"].isin(df_g[mask_g_AA]["Genotype"]) 
mask_p_BB = df_p["Genotype"].isin(df_g[mask_g_BB]["Genotype"]) 
mask_p_AB = df_p["Genotype"].isin(df_g[mask_g_AB]["Genotype"]) 
mask_p_BA = df_p["Genotype"].isin(df_g[mask_g_BA]["Genotype"])

In [28]:
mask_g_AA

0      False
1      False
2      False
3      False
4      False
       ...
115    False
116     True
117     True
118     True
119     True
Length: 120, dtype: bool

In [29]:
df_p[mask_g_AA]["HEI"].mean()

np.float64(52.0)

In [30]:
df_p[mask_g_AB]["HEI"].mean()

np.float64(54.8)

In [31]:
df_p[mask_g_BA]["HEI"].mean()

np.float64(56.3)

In [32]:
df_p[mask_g_BB]["HEI"].mean()

np.float64(62.46356770556324)